[package]
name = "rust_async_chat"
version = "0.1.0"
authors = ["yangyang <ofyang@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
async-std = "1.2.0"